### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by sagarpandyansit** [varadbhogayata/varadbhogayata.github.io#14]
As you suggest in the installation step, I cloned the repository and try to run index.html but, It had no effect
![Screenshot from 2020-10-01 12-11-19](https://user-images.githubusercontent.com/31953933/94776481-6ca0cd00-03df-11eb-836e-1cddf3ad76d5.png)
.

**Comment by varadbhogayata** [comment]
Hi Sagar,

This might happen if there is no internet connection when you are trying to run index.html. Please try again with internet connection. Also, use "Live Server" extension from VS Code for running index.html, which will launch a local development server at port 5500.

Feel free to reach out to me on LinkedIn, if you are facing the same issue.

Thank you.

**Comment by sagarpandyansit** [comment]
Hi Varad,
It is an amazing portfolio website. Thank you.
